# Generated by Django 3.2 on 2025-01-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyRegister_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('registration_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('adress', models.CharField(max_length=200)),
                ('industry_type', models.CharField(max_length=50)),
            ],
        ),
    ]
