# Generated by Django 3.2 on 2025-01-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyregister_model',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='companyregister_model',
            old_name='phone_no',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='companyregister_model',
            old_name='registration_no',
            new_name='registration_number',
        ),
    ]
